### ISSUE TITLE
How to compile for itch.io?

### ISSUE THREAD

**Issue by a96lex** [tank-king/BreakPong#1]
Hello,

I found your game listed on an itch.io [list](https://itch.io/c/2563651/pygame-wasm) made by [pmp-p](https://github.com/pmp-p), creator of pygbag.

I am also trying to build my game and add it to itch.io [here](https://alex-pf.itch.io/tank-game), but i am not getting the results you did (in terms of embedding the game in the page, and allowing fullscreen).

May I ask how did you achieve the results?

I am just trying to:
```shell
python -m pygbag --app_name tank --archive pygame-tank-game
```

But when i publish on github i get this layout:
<img width="1440" alt="Screenshot 2022-07-21 at 11 32 02" src="https://user-images.githubusercontent.com/62766970/180181128-7709128d-01e1-4e8a-a92e-461ecf9602e0.png">

**Comment by tank-king** [comment]
Hi! For Breakpong I did not compile the web version using pygbag, I used HTML + javascript to build a web porting. I believe pmp-p did a web port of the game on his own. But my latest game as of now uses pygbag for the web build: https://tank-king.itch.io/dimensions

What I did is run: `pygbag --archive --template template.tmpl --folder-name`

The template.tmpl file is basically what ensures the layout of the game is
If you can edit the template file then you can achieve a customized effect to how your page is displayed. If you want detailed info on how to do that, you can ask me here, but I recommend going to the pygame discord server  [https://discord.gg/t3g7YjK7rw] in the pygame-web channel, where pmp-p can guide you in details how to do that.

But the answer to how to make a fullscreen mode and hide the console is to edit the template file.

**Comment by a96lex** [comment]
Cool, I actually checked all your games, and I thought you also used pygbag in Breakpong my bad.

Okay, thank you very much, ill check the discord :)

I am closing the issue

**Comment by tank-king** [comment]
:)))))
